# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env: 
      REACT_APP_BASEURL: "https://andreev.work/copoetry"
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PRIVATEKEY }}
        user: ${{ secrets.USER }}
        script: whoami
    - uses: actions/checkout@v2
    - name: Build w/ Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./build
        remote: ./copoetry/front-end/build
        host: ${{ secrets.HOST }}
        privateKey: ${{ secrets.PRIVATEKEY }}
        user: ${{ secrets.USER }}
