name: Test, Build, and Deploy via SSH

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env: 
      REACT_APP_BASEURL: "https://copoetry.andreev.work"
      REACT_APP_API_BASEURL: "https://copoetry.andreev.work"
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present
    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./build
        remote: ./copoetry/front-end/build
        host: ${{ secrets.HOST }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
        username: ${{ secrets.USER }}
